export const QuestionColumns = [
	{
		Header: 'Question',
		accessor: 'question',
		title: 'question',
		dataIndex: 'question',
		key: 'question',
		width: 400,
		className: 'text-white bg-gray-800 p-2 border-r-2 border-b-2',
		rowClassName: 'bg-black-ripon',
	},
	{
		Header: 'Question Type',
		accessor: 'question_type',
		title: 'question_type',
		dataIndex: 'question_type',
		key: 'question_type',
		width: 400,
		className: 'text-white bg-gray-800 p-2 border-r-2 border-b-2',
		rowClassName: 'bg-black-ripon',
	},
	{
		Header: 'Level',
		accessor: 'level',
		title: 'level',
		dataIndex: 'level',
		key: 'level',
		width: 400,
		className: 'text-white bg-gray-800 p-2 border-r-2 border-b-2',
		rowClassName: 'bg-black-ripon',
	},
	{
		Header: 'Module',
		accessor: 'modules',
		title: 'modules',
		dataIndex: 'modules',
		key: 'modules',
		width: 400,
		className: 'text-white bg-gray-800 p-2 border-r-2 border-b-2',
		rowClassName: 'bg-black-ripon',
	},

	{
		Header: 'Status',
		accessor: 'status',
		title: 'Status',
		dataIndex: 'status',
		key: 'status',
		width: 400,
		className: 'text-white bg-gray-800 p-2 border-r-2 border-b-2',
	},
	{
		Header: 'Action',
		accessor: 'action',
		title: 'Action',
		dataIndex: 'action',
		key: 'operations',
		width: 250,
		className: 'text-white bg-gray-600 p-2 border-b-2',
	},
]
