version: '3.4'

services:
  prisma:
    image: prisma
    restart: unless-stopped
    container_name: prisma
    networks:
      - my-network
    ports:
      - "15432:5432"
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - prisma:/var/lib/prisma/data
volumes:
  prisma:
networks:
  my-network: