import Head from 'next/head'
import Login from './login/index'
import 'regenerator-runtime/runtime'

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link
					rel='icon'
					href='/favicon.ico'
				/>
			</Head>

			<Login />
		</>
	)
}
