import Head from 'next/head'
import Login from './login/index'
import 'regenerator-runtime/runtime'
import { ButtonComponent } from '../components/common/micro/button'

import { useSession, signIn, signOut } from 'next-auth/react'

export default function Home() {
	// const { data: session } = useSession()

	console.log('sessisong')

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link
					rel='icon'
					href='/favicon.ico'
				/>
			</Head>

			<Login />
		</>
	)
}
