import Head from 'next/head'
import Image from 'next/image'
// import styles from '../styles/Home.module.css'
import Login from '../../components/login'


export default function login () {
  return (
    <div >
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
      
      </Head>


   <Login/>

      
    </div>
  )
}
