export const QuizColumns = [
	{
		Header: 'Quiz',
		accessor: 'quiz',
		title: 'quiz',
		dataIndex: 'quiz',
		key: 'quiz',
		width: 400,
		className: 'text-white bg-gray-800 p-2 border-r-2 border-b-2',
		rowClassName: 'bg-black-ripon',
	},
	{
		Header: 'Level',
		accessor: 'level',
		title: 'level',
		dataIndex: 'level',
		key: 'level',
		width: 400,
		className: 'text-white bg-gray-800 p-2 border-r-2 border-b-2',
	},
	{
		Header: 'Modules',
		accessor: 'modules',
		title: 'modules',
		dataIndex: 'modules',
		key: 'modules',
		width: 400,
		className: 'text-white bg-gray-800 p-2 border-r-2 border-b-2',
	},

	{
		Header: 'Start Date ',
		accessor: 'start_date',
		title: 'start_date',
		dataIndex: 'start_date',
		key: 'start_date',
		width: 400,
		className: 'text-white bg-gray-800 p-2 border-r-2 border-b-2',
	},
	{
		Header: 'End Date',
		accessor: 'end_date',
		title: 'end_date',
		dataIndex: 'end_date',
		key: 'end_date',
		width: 400,
		className: 'text-white bg-gray-800 p-2 border-r-2 border-b-2',
	},

	{
		Header: 'Status',
		accessor: 'status',
		title: 'Status',
		dataIndex: 'status',
		key: 'status',
		width: 400,
		className: 'text-white bg-gray-800 p-2 border-r-2 border-b-2',
	},
	{
		Header: 'Action',
		accessor: 'action',
		title: 'Action',
		dataIndex: 'action',
		key: 'operations',
		width: 250,
		className: 'text-white bg-gray-600 p-2 border-b-2',
	},
]
